version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      # 取消注释并设置此变量以启用密码保护
      # - APP_PASSWORD=your_password
    restart: always
    volumes:
      - ./data/account:/app/account
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
